version: "3.9"

services:
  clonebot:
    image: kerensekali/clonebot:latest
    container_name: clonebot
    environment:
      - telegram_token=${BOT_TOKEN}
      - user_ids=${ALLOW_USERS}
      - group_ids=${ALLOW_GROUPS}
    ports:
      - 8080:8080
    restart: unless-stopped
